Repository AY2223S2-CS2103T-T13-2/tp, pull requests merged in 2023-03, with the labels that each got.

#35 Add User Stories for `Delete`, `List` and NFRs
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#42 Add DG glossary
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#43 V1.1: Seeu Sim's PPP and AboutUs
  docs/AboutUs.md
  docs/images/alson001.png
  docs/images/developers/johndoe.png
  docs/images/filbertphang.png
  docs/images/jamesliuzx.png
  docs/images/seeusim.png
  docs/images/zhtang29.png
  docs/team/alson001.md
  docs/team/filbertphang.md
  docs/team/jamesliuzx.md
  docs/team/seeusim.md
  docs/team/zhtang29.md
Labels: type.Chore, priority.Medium

#45 V1.1: Alson's PPP
  docs/team/alson001.md
Labels: type.Chore, priority.Medium

#46 V1.1: Filbert's PPP
  docs/team/filbertphang.md
Labels: type.Chore, priority.Medium

#73 V1.2: Refactor Parser for "Add", "List", "Clear", "Exit" and their commands #72
  src/main/java/seedu/recipe/MainApp.java
  src/main/java/seedu/recipe/logic/Logic.java
  src/main/java/seedu/recipe/logic/LogicManager.java
  src/main/java/seedu/recipe/logic/commands/AddCommand.java
  src/main/java/seedu/recipe/logic/commands/ClearCommand.java
  src/main/java/seedu/recipe/logic/commands/ExitCommand.java
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/logic/parser/functional/CheckedParseFunction.java
  src/main/java/seedu/recipe/logic/parser/functional/TryUtil.java
  src/main/java/seedu/recipe/model/Model.java
  src/main/java/seedu/recipe/model/ModelManager.java
  src/main/java/seedu/recipe/model/ReadOnlyRecipeBook.java
  src/main/java/seedu/recipe/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/recipe/model/RecipeBook.java
  src/main/java/seedu/recipe/model/UserPrefs.java
  src/main/java/seedu/recipe/model/recipe/RecipeDuration.java
  src/main/java/seedu/recipe/model/recipe/RecipePortion.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeDurationInvalidArgumentLengthException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeDurationInvalidDurationException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipePortionInvalidArgumentException.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonRecipeBookStorage.java
  src/main/java/seedu/recipe/storage/JsonSerializableRecipeBook.java
  src/main/java/seedu/recipe/storage/RecipeBookStorage.java
  src/main/java/seedu/recipe/storage/Storage.java
  src/main/java/seedu/recipe/storage/StorageManager.java
  src/test/java/seedu/recipe/logic/LogicManagerTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandTest.java
  src/test/java/seedu/recipe/logic/commands/ClearCommandTest.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/recipe/logic/commands/EditCommandTest.java
  src/test/java/seedu/recipe/logic/commands/ListCommandTest.java
  src/test/java/seedu/recipe/model/AddressBookTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/recipe/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/recipe/storage/StorageManagerTest.java
  src/test/java/seedu/recipe/testutil/AddressBookBuilder.java
  src/test/java/seedu/recipe/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High, severity.High

#74 V1.2: Refactor Parser for "Edit", "Delete", "Find", "Help" and their commands
  src/main/java/seedu/recipe/logic/commands/EditCommand.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/ui/HelpWindow.java
Labels: type.Enhancement, priority.High, severity.High

#75 V1.2: Refactor Parser Classes and their respective Command classes
  src/main/java/seedu/recipe/MainApp.java
  src/main/java/seedu/recipe/logic/Logic.java
  src/main/java/seedu/recipe/logic/LogicManager.java
  src/main/java/seedu/recipe/logic/commands/AddCommand.java
  src/main/java/seedu/recipe/logic/commands/ClearCommand.java
  src/main/java/seedu/recipe/logic/commands/EditCommand.java
  src/main/java/seedu/recipe/logic/commands/ExitCommand.java
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/CliSyntax.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/logic/parser/functional/CheckedParseFunction.java
  src/main/java/seedu/recipe/logic/parser/functional/TryUtil.java
  src/main/java/seedu/recipe/model/Model.java
  src/main/java/seedu/recipe/model/ModelManager.java
  src/main/java/seedu/recipe/model/ReadOnlyRecipeBook.java
  src/main/java/seedu/recipe/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/recipe/model/RecipeBook.java
  src/main/java/seedu/recipe/model/UserPrefs.java
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/Name.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/RecipeDuration.java
  src/main/java/seedu/recipe/model/recipe/RecipeIngredient.java
  src/main/java/seedu/recipe/model/recipe/RecipePortion.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeDurationInvalidArgumentLengthException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeDurationInvalidDurationException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeDurationNotPresentException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeIngredientUnitMissingException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipePortionInvalidArgumentException.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipePortionNotPresentException.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonRecipeBookStorage.java
  src/main/java/seedu/recipe/storage/JsonSerializableRecipeBook.java
  src/main/java/seedu/recipe/storage/RecipeBookStorage.java
  src/main/java/seedu/recipe/storage/Storage.java
  src/main/java/seedu/recipe/storage/StorageManager.java
  src/main/java/seedu/recipe/ui/HelpWindow.java
  src/test/java/seedu/recipe/logic/LogicManagerTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandTest.java
  src/test/java/seedu/recipe/logic/commands/ClearCommandTest.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/recipe/logic/commands/EditCommandTest.java
  src/test/java/seedu/recipe/logic/commands/ListCommandTest.java
  src/test/java/seedu/recipe/model/AddressBookTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/recipe/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/recipe/storage/StorageManagerTest.java
  src/test/java/seedu/recipe/testutil/AddressBookBuilder.java
  src/test/java/seedu/recipe/testutil/TypicalPersons.java
Labels: type.Epic, type.Enhancement, priority.High, severity.High

#86 V1.2: Fix JSON serialization and deserialization
  build.gradle
  src/main/java/seedu/recipe/commons/util/JsonUtil.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/RecipeDuration.java
  src/main/java/seedu/recipe/model/recipe/RecipePortion.java
  src/main/java/seedu/recipe/model/recipe/unit/PortionUnit.java
  src/main/java/seedu/recipe/model/recipe/unit/Unit.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonAdaptedName.java
  src/main/java/seedu/recipe/storage/JsonAdaptedPortionUnit.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipeDuration.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipePortion.java
  src/main/java/seedu/recipe/storage/JsonAdaptedTimeUnit.java
Labels: type.Enhancement, priority.High

#88 Add preliminary test cases for Recipe, other models
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/Name.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/RecipePortion.java
  src/main/java/seedu/recipe/model/tag/Tag.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/test/java/seedu/recipe/logic/LogicManagerTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandTest.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/EditCommandTest.java
  src/test/java/seedu/recipe/logic/commands/EditRecipeDescriptorTest.java
  src/test/java/seedu/recipe/logic/commands/FindCommandTest.java
  src/test/java/seedu/recipe/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/logic/parser/RecipeBookParserTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/model/RecipeBookTest.java
  src/test/java/seedu/recipe/model/recipe/AddressTest.java
  src/test/java/seedu/recipe/model/recipe/EmailTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/storage/JsonRecipeBookStorageTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeUtil.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High, severity.Medium

#89 V1.2: Add test coverage for Recipe Model, and other classes progressively
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/unit/Unit.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipe.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High, severity.High

#92 Add basic test coverage for `models.recipe` package
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/Name.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/RecipeDuration.java
  src/main/java/seedu/recipe/model/recipe/RecipeIngredient.java
  src/main/java/seedu/recipe/model/recipe/RecipePortion.java
  src/main/java/seedu/recipe/model/recipe/Step.java
  src/main/java/seedu/recipe/model/recipe/UniqueRecipeList.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeIngredientUnitMissingException.java
  src/main/java/seedu/recipe/model/recipe/unit/IngredientAmountUnit.java
  src/main/java/seedu/recipe/model/recipe/unit/Unit.java
  src/main/java/seedu/recipe/model/tag/Tag.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeListPanel.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/recipe/logic/LogicManagerTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/recipe/logic/commands/AddCommandTest.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/EditCommandTest.java
  src/test/java/seedu/recipe/logic/commands/EditRecipeDescriptorTest.java
  src/test/java/seedu/recipe/logic/commands/FindCommandTest.java
  src/test/java/seedu/recipe/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/logic/parser/RecipeBookParserTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/model/RecipeBookTest.java
  src/test/java/seedu/recipe/model/recipe/AddressTest.java
  src/test/java/seedu/recipe/model/recipe/EmailTest.java
  src/test/java/seedu/recipe/model/recipe/IngredientTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/NameTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeDurationTest.java
  src/test/java/seedu/recipe/model/recipe/RecipePortionTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/model/recipe/StepTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/model/recipe/unit/UnitTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/storage/JsonRecipeBookStorageTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeUtil.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High, severity.High

#80 [WIP] V1.2: Cleanup, Code Style, and Code Quality
  src/main/java/seedu/recipe/logic/Logic.java
  src/main/java/seedu/recipe/logic/LogicManager.java
  src/main/java/seedu/recipe/logic/commands/AddCommand.java
  src/main/java/seedu/recipe/logic/commands/ClearCommand.java
  src/main/java/seedu/recipe/logic/commands/DeleteCommand.java
  src/main/java/seedu/recipe/logic/commands/EditCommand.java
  src/main/java/seedu/recipe/logic/commands/FindCommand.java
  src/main/java/seedu/recipe/logic/commands/ListCommand.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/RecipeBookParser.java
  src/main/java/seedu/recipe/model/Model.java
  src/main/java/seedu/recipe/model/ModelManager.java
  src/main/java/seedu/recipe/model/UserPrefs.java
  src/main/java/seedu/recipe/model/recipe/RecipeDuration.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/ui/MainWindow.java
  src/test/java/seedu/recipe/logic/parser/RecipeBookParserTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/model/UserPrefsTest.java
  src/test/java/seedu/recipe/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Chore, priority.Medium

#77 [WIP] V1.2: Add documentation and do some minor refactoring
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/recipe/model/Model.java
  src/main/java/seedu/recipe/model/ModelManager.java
  src/main/java/seedu/recipe/model/ReadOnlyRecipeBook.java
  src/main/java/seedu/recipe/model/RecipeBook.java
  src/main/java/seedu/recipe/model/UserPrefs.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/RecipeDuration.java
  src/main/java/seedu/recipe/model/recipe/RecipePortion.java
  src/main/java/seedu/recipe/model/recipe/unit/PortionUnit.java
  src/main/java/seedu/recipe/model/recipe/unit/TimeUnit.java
  src/main/java/seedu/recipe/model/recipe/unit/Unit.java
  src/main/java/seedu/recipe/ui/HelpWindow.java
Labels: type.Chore, priority.Medium

#114 V1.3: Refactor Recipe `ingredients` field to a `Hashtable`
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/logic/util/RecipeDescriptor.java
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeQuantityInvalidArgumentException.java
  src/main/java/seedu/recipe/model/recipe/ingredient/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientParser.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientQuantity.java
  src/main/java/seedu/recipe/model/recipe/unit/RecipeIngredientQuantityUnit.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonSerializableRecipeBook.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedRecipe.java
  src/test/data/JsonSerializableRecipeBookTest/duplicateRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeRecipeBook.json
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/model/recipe/IngredientBuilderTest.java
  src/test/java/seedu/recipe/model/recipe/IngredientTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/model/util/SampleDataUtilTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/storage/JsonSerializableRecipeBookTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High, severity.High

#96 UI Code for V.1.3 Features
  src/main/java/seedu/recipe/ui/MainWindow.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeForm.java
  src/main/java/seedu/recipe/ui/RecipePopup.java
  src/main/java/seedu/recipe/ui/events/AddRecipeEvent.java
  src/main/java/seedu/recipe/ui/events/DeleteRecipeEvent.java
  src/main/java/seedu/recipe/ui/events/EditRecipeEvent.java
  src/main/resources/view/RecipeForm.fxml
  src/main/resources/view/RecipeListCard.fxml
  src/main/resources/view/RecipePopup.fxml
Labels: type.Epic, priority.Medium

#125 V1.3: Add DG for Model package
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Enhancement, priority.High, severity.Medium

#126 V1.3: DG for `UI` package - James
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High

#132 Merge v1.3documentation into master
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
  docs/team/filbertphang.md
Labels: type.Enhancement, priority.High, severity.Medium

#117 V1.3ui
  docs/DeveloperGuide.md
  src/main/java/seedu/recipe/ui/MainWindow.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeForm.java
  src/main/java/seedu/recipe/ui/RecipePopup.java
  src/main/java/seedu/recipe/ui/events/AddRecipeEvent.java
  src/main/java/seedu/recipe/ui/events/DeleteRecipeEvent.java
  src/main/java/seedu/recipe/ui/events/EditRecipeEvent.java
  src/main/resources/view/RecipeForm.fxml
  src/main/resources/view/RecipeListCard.fxml
  src/main/resources/view/RecipePopup.fxml
Labels: priority.High

#138 V1.3: Refactor Recipe Fields
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/logic/util/RecipeDescriptor.java
  src/main/java/seedu/recipe/model/recipe/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeQuantityInvalidArgumentException.java
  src/main/java/seedu/recipe/model/recipe/ingredient/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientInformation.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientParser.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientQuantity.java
  src/main/java/seedu/recipe/model/recipe/unit/RecipeIngredientQuantityUnit.java
  src/main/java/seedu/recipe/model/util/IngredientUtil.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedSubstitutionIngredient.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipePopup.java
  src/test/data/JsonRecipeBookStorageTest/invalidAndValidRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/duplicateRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeRecipeBook.json
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/model/recipe/ingredient/IngredientBuilderTest.java
  src/test/java/seedu/recipe/model/recipe/ingredient/IngredientTableTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/storage/JsonSerializableRecipeBookTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High, severity.High

#137 V1.3: Refactor recipe fields to a `HashMap`
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/logic/util/RecipeDescriptor.java
  src/main/java/seedu/recipe/model/recipe/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeQuantityInvalidArgumentException.java
  src/main/java/seedu/recipe/model/recipe/ingredient/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientInformation.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientParser.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientQuantity.java
  src/main/java/seedu/recipe/model/recipe/unit/RecipeIngredientQuantityUnit.java
  src/main/java/seedu/recipe/model/util/IngredientUtil.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedSubstitutionIngredient.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeForm.java
  src/main/java/seedu/recipe/ui/RecipePopup.java
  src/test/data/JsonRecipeBookStorageTest/invalidAndValidRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/duplicateRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeRecipeBook.json
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/model/recipe/ingredient/IngredientBuilderTest.java
  src/test/java/seedu/recipe/model/recipe/ingredient/IngredientTableTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/storage/JsonSerializableRecipeBookTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Enhancement, priority.High, severity.High

#127 V1.3: Implement Find by Tag
  src/main/java/seedu/recipe/commons/core/Messages.java
  src/main/java/seedu/recipe/logic/commands/FindCommand.java
  src/main/java/seedu/recipe/logic/parser/FindCommandParser.java
  src/main/java/seedu/recipe/logic/util/FindUtil.java
  src/main/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/PropertyCollectionContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/PropertyNameContainsKeywordsPredicate.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/FindCommandTest.java
  src/test/java/seedu/recipe/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/RecipeBookParserTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/PropertyCollectionContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/PropertyNameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.High

#140 V1.3B Final UI Functionalities
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/logic/util/RecipeDescriptor.java
  src/main/java/seedu/recipe/model/recipe/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/exceptions/RecipeQuantityInvalidArgumentException.java
  src/main/java/seedu/recipe/model/recipe/ingredient/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientInformation.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientParser.java
  src/main/java/seedu/recipe/model/recipe/ingredient/IngredientQuantity.java
  src/main/java/seedu/recipe/model/recipe/unit/RecipeIngredientQuantityUnit.java
  src/main/java/seedu/recipe/model/util/IngredientUtil.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/storage/jsonadapters/JsonAdaptedSubstitutionIngredient.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeForm.java
  src/main/java/seedu/recipe/ui/RecipePopup.java
  src/test/data/JsonRecipeBookStorageTest/invalidAndValidRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/duplicateRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipeRecipeBook.json
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/RecipeTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/model/recipe/ingredient/IngredientBuilderTest.java
  src/test/java/seedu/recipe/model/recipe/ingredient/IngredientTableTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/storage/JsonSerializableRecipeBookTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: priority.High

#185 V1.3: Find enhancements
  src/main/java/seedu/recipe/commons/core/Messages.java
  src/main/java/seedu/recipe/logic/commands/FindCommand.java
  src/main/java/seedu/recipe/logic/parser/FindCommandParser.java
  src/main/java/seedu/recipe/logic/util/FindUtil.java
  src/main/java/seedu/recipe/model/recipe/IngredientBuilder.java
  src/main/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/PropertyCollectionContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/PropertyNameContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/ingredient/Ingredient.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/FindCommandTest.java
  src/test/java/seedu/recipe/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/RecipeBookParserTest.java
  src/test/java/seedu/recipe/model/ModelManagerTest.java
  src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/PropertyCollectionContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/PropertyNameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.High

#148 V1.3: Implement new `sub` command
  docs/DeveloperGuide.md
  src/main/java/seedu/recipe/commons/core/Messages.java
  src/main/java/seedu/recipe/logic/commands/SubCommand.java
  src/main/java/seedu/recipe/logic/parser/RecipeBookParser.java
  src/main/java/seedu/recipe/logic/parser/SubCommandParser.java
  src/main/java/seedu/recipe/model/ModelManager.java
  src/main/java/seedu/recipe/model/ReadOnlyRecipeBook.java
  src/main/java/seedu/recipe/model/RecipeBook.java
  src/main/java/seedu/recipe/model/recipe/ingredient/Ingredient.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/model/util/SubstitutionsUtil.java
  src/main/java/seedu/recipe/ui/MainWindow.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/commands/SubCommandTest.java
  src/test/java/seedu/recipe/model/RecipeBookTest.java
Labels: type.Enhancement, priority.High

#194 V1.3b export
  src/main/java/seedu/recipe/logic/Logic.java
  src/main/java/seedu/recipe/logic/LogicManager.java
  src/main/java/seedu/recipe/logic/commands/ExportCommand.java
  src/main/java/seedu/recipe/logic/commands/ImportCommand.java
  src/main/java/seedu/recipe/storage/ExportManager.java
  src/main/java/seedu/recipe/storage/ImportManager.java
  src/main/java/seedu/recipe/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#203 V1.3: Add JavaDocs for Mainwindow
  src/main/java/seedu/recipe/logic/commands/ExportCommand.java
  src/main/java/seedu/recipe/storage/ImportManager.java
  src/main/java/seedu/recipe/ui/MainWindow.java
Labels: type.Enhancement, priority.Medium
